using CppAst;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace JoltPhysicsGen
{
	public class CsCodeGenerator
	{
		public static readonly CsCodeGenerator Instance = new();

		private const string Namespace = "Evergine.Bindings.JoltPhysics";
		private const string NativeClass = "JoltPhysicsNative";
		private const string DllName = "JoltC";

		public void Generate(CppCompilation compilation, string outputPath)
		{
			// 1. Pre-collect opaque handle names (forward-declared structs with no definition)
			CollectOpaqueHandles(compilation);

			// 2. Pre-collect delegate names (function pointer typedefs)
			CollectDelegateNames(compilation);

			// 3. Pre-collect blittable struct names (structs with definitions)
			CollectBlittableStructs(compilation);

			// 4. Generate each file
			GenerateConstants(compilation, outputPath);
			GenerateEnums(compilation, outputPath);
			GenerateDelegates(compilation, outputPath);
			GenerateStructs(compilation, outputPath);
			GenerateFunctions(compilation, outputPath);
		}

		private void CollectOpaqueHandles(CppCompilation compilation)
		{
			var definedStructs = new HashSet<string>();

			// First pass: find all structs that have actual definitions (fields)
			foreach (var cls in compilation.Classes)
			{
				if (cls.ClassKind == CppClassKind.Struct && cls.Fields.Count > 0)
				{
					definedStructs.Add(cls.Name);
				}
			}

			// Second pass: find typedefs to struct types that are NOT defined
			foreach (var td in compilation.Typedefs)
			{
				// Skip primitive aliases
				if (td.ElementType is CppPrimitiveType) continue;
				if (td.ElementType is CppPointerType) continue;
				if (td.ElementType is CppEnum) continue;

				var innerType = td.ElementType;
				if (innerType is CppQualifiedType q)
					innerType = q.ElementType;

				if (innerType is CppClass cls && !definedStructs.Contains(cls.Name))
				{
					if (!Helpers.OpaqueHandles.Contains(td.Name))
					{
						Helpers.OpaqueHandles.Add(td.Name);
					}
				}
			}

			// Also add struct forward declarations from Classes collection
			foreach (var cls in compilation.Classes)
			{
				if (cls.ClassKind == CppClassKind.Struct && cls.Fields.Count == 0 && !definedStructs.Contains(cls.Name))
				{
					if (!Helpers.OpaqueHandles.Contains(cls.Name))
					{
						Helpers.OpaqueHandles.Add(cls.Name);
					}
				}
			}

			Console.WriteLine($"Opaque handles: {Helpers.OpaqueHandles.Count}");
		}

		private void CollectDelegateNames(CppCompilation compilation)
		{
			foreach (var td in compilation.Typedefs)
			{
				var type = td.ElementType;
				if (type is CppPointerType ptr && ptr.ElementType is CppFunctionType)
				{
					Helpers.DelegateNames.Add(td.Name);
				}
			}

			Console.WriteLine($"Delegates: {Helpers.DelegateNames.Count}");
		}

		private void CollectBlittableStructs(CppCompilation compilation)
		{
			foreach (var cls in compilation.Classes)
			{
				if (cls.ClassKind == CppClassKind.Struct && cls.Fields.Count > 0)
				{
					Helpers.BlittableStructs.Add(cls.Name);
				}
			}

			Console.WriteLine($"Blittable structs: {Helpers.BlittableStructs.Count}");
		}

		// ==================================================================
		// Constants
		// ==================================================================
		private void GenerateConstants(CppCompilation compilation, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Constants.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// Auto-generated by JoltPhysicsGen — do not edit manually.");
			writer.WriteLine("using System;");
			writer.WriteLine();
			writer.WriteLine($"namespace {Namespace}");
			writer.WriteLine("{");
			writer.WriteLine($"\tpublic static unsafe partial class {NativeClass}");
			writer.WriteLine("\t{");

			foreach (var macro in compilation.Macros)
			{
				if (string.IsNullOrWhiteSpace(macro.Value)) continue;

				var name = macro.Name;
				var value = macro.Value;

				// Skip internal/header guard macros
				if (name.StartsWith("_") || name.StartsWith("JOLTC_H") ||
					name.Contains("_H_") || name.EndsWith("_H") ||
					name == "JOLTC_API" || name == "JOLTC_EXPORTS" ||
					name == "__cplusplus")
					continue;

				// Determine type from value
				string type;
				string csValue;

				if (value.StartsWith("0x") || value.StartsWith("0X"))
				{
					// Hex value
					if (value.Contains("U") || value.Contains("u"))
					{
						type = "uint";
						csValue = value.TrimEnd('U', 'u');
					}
					else
					{
						type = "uint";
						csValue = value;
					}
				}
				else if (value.StartsWith("(~"))
				{
					// Bitwise not pattern like (~0U)
					type = "uint";
					csValue = "~0U";
				}
				else if (int.TryParse(value, out _))
				{
					type = "int";
					csValue = value;
				}
				else if (value.EndsWith("U") && uint.TryParse(value.TrimEnd('U', 'u'), out _))
				{
					type = "uint";
					csValue = value;
				}
				else if (value.EndsWith("f") || value.Contains("."))
				{
					type = "float";
					csValue = value;
				}
				else
				{
					// Skip complex macros
					continue;
				}

				writer.WriteLine($"\t\tpublic const {type} {name} = {csValue};");
			}

			writer.WriteLine("\t}");
			writer.WriteLine("}");

			Console.WriteLine($"  Generated: Constants.cs");
		}

		// ==================================================================
		// Enums
		// ==================================================================
		private void GenerateEnums(CppCompilation compilation, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Enums.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// Auto-generated by JoltPhysicsGen — do not edit manually.");
			writer.WriteLine("using System;");
			writer.WriteLine();
			writer.WriteLine($"namespace {Namespace}");
			writer.WriteLine("{");

			foreach (var cppEnum in compilation.Enums)
			{
				if (cppEnum.Items.Count == 0) continue;
				if (cppEnum.IsAnonymous) continue;

				var enumName = cppEnum.Name;

				// Detect [Flags] by checking if any typedef named EnumNameFlags exists
				bool isFlags = compilation.Typedefs.Any(t => t.Name == enumName + "Flags");
				// Also detect by name pattern
				if (enumName.Contains("DOFs") || enumName.Contains("Flags"))
					isFlags = true;

				Helpers.WriteComment(writer, cppEnum.Comment, "\t");

				if (isFlags)
					writer.WriteLine("\t[Flags]");

				writer.WriteLine($"\tpublic enum {enumName}");
				writer.WriteLine("\t{");

				foreach (var item in cppEnum.Items)
				{
					Helpers.WriteComment(writer, item.Comment, "\t\t");
					writer.WriteLine($"\t\t{item.Name} = {item.Value},");
				}

				writer.WriteLine("\t}");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"  Generated: Enums.cs");
		}

		// ==================================================================
		// Delegates
		// ==================================================================
		private void GenerateDelegates(CppCompilation compilation, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Delegates.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// Auto-generated by JoltPhysicsGen — do not edit manually.");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine();
			writer.WriteLine($"namespace {Namespace}");
			writer.WriteLine("{");

			foreach (var td in compilation.Typedefs)
			{
				var type = td.ElementType;
				if (type is CppPointerType ptr && ptr.ElementType is CppFunctionType funcType)
				{
					var delegateName = td.Name;
					var returnType = Helpers.ConvertReturnType(funcType.ReturnType);

					var parameters = new List<string>();
					foreach (var param in funcType.Parameters)
					{
						var paramType = Helpers.ConvertParameterType(param.Type);
						var paramName = string.IsNullOrEmpty(param.Name)
							? $"arg{funcType.Parameters.IndexOf(param)}"
							: Helpers.EscapeReservedKeyword(param.Name);
						parameters.Add($"{paramType} {paramName}");
					}

					var paramStr = string.Join(", ", parameters);

					writer.WriteLine($"\t[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
					writer.WriteLine($"\tpublic unsafe delegate {returnType} {delegateName}({paramStr});");
					writer.WriteLine();
				}
			}

			writer.WriteLine("}");

			Console.WriteLine($"  Generated: Delegates.cs");
		}

		// ==================================================================
		// Structs
		// ==================================================================
		private void GenerateStructs(CppCompilation compilation, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Structs.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// Auto-generated by JoltPhysicsGen — do not edit manually.");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine();
			writer.WriteLine($"namespace {Namespace}");
			writer.WriteLine("{");

			// Track emitted structs to avoid duplicates
			var emitted = new HashSet<string>();

			foreach (var cls in compilation.Classes)
			{
				if (cls.ClassKind != CppClassKind.Struct) continue;
				if (cls.Fields.Count == 0) continue; // Skip forward declarations
				if (emitted.Contains(cls.Name)) continue;
				emitted.Add(cls.Name);

				bool isUnion = cls.ClassKind == CppClassKind.Union;

				// Check if any fields have FieldOffset (union)
				bool hasUnionFields = cls.Fields.Any(f =>
					f.Type is CppClass nested && nested.ClassKind == CppClassKind.Union);

				Helpers.WriteComment(writer, cls.Comment, "\t");

				if (isUnion)
				{
					writer.WriteLine("\t[StructLayout(LayoutKind.Explicit)]");
				}
				else
				{
					writer.WriteLine("\t[StructLayout(LayoutKind.Sequential)]");
				}

				writer.WriteLine($"\tpublic unsafe partial struct {cls.Name}");
				writer.WriteLine("\t{");

				foreach (var field in cls.Fields)
				{
					var fieldName = Helpers.EscapeReservedKeyword(field.Name);
					var fieldType = Helpers.ConvertFieldType(field.Type, out int fixedSize);

					if (isUnion)
					{
						writer.WriteLine($"\t\t[FieldOffset(0)]");
					}

					if (fixedSize > 0)
					{
						// Fixed-size array
						if (fieldType == "float" || fieldType == "int" || fieldType == "uint" ||
							fieldType == "byte" || fieldType == "short" || fieldType == "ushort" ||
							fieldType == "long" || fieldType == "ulong" || fieldType == "double" ||
							fieldType == "sbyte")
						{
							writer.WriteLine($"\t\tpublic fixed {fieldType} {fieldName}[{fixedSize}];");
						}
						else
						{
							// Non-primitive fixed arrays: emit individual fields
							for (int i = 0; i < fixedSize; i++)
							{
								writer.WriteLine($"\t\tpublic {fieldType} {fieldName}_{i};");
							}
						}
					}
					else
					{
						writer.WriteLine($"\t\tpublic {fieldType} {fieldName};");
					}
				}

				writer.WriteLine("\t}");
				writer.WriteLine();
			}

			writer.WriteLine("}");

			Console.WriteLine($"  Generated: Structs.cs");
		}

		// ==================================================================
		// Functions
		// ==================================================================
		private void GenerateFunctions(CppCompilation compilation, string outputPath)
		{
			var filePath = Path.Combine(outputPath, "Functions.cs");
			using var writer = new StreamWriter(filePath);

			writer.WriteLine("// Auto-generated by JoltPhysicsGen — do not edit manually.");
			writer.WriteLine("using System;");
			writer.WriteLine("using System.Runtime.InteropServices;");
			writer.WriteLine();
			writer.WriteLine($"namespace {Namespace}");
			writer.WriteLine("{");
			writer.WriteLine($"\tpublic static unsafe partial class {NativeClass}");
			writer.WriteLine("\t{");

			foreach (var func in compilation.Functions)
			{
				// Skip inline and template functions
				if (func.Flags.HasFlag(CppFunctionFlags.Inline)) continue;
				if (func.Flags.HasFlag(CppFunctionFlags.FunctionTemplate)) continue;

				var returnType = Helpers.ConvertReturnType(func.ReturnType);
				var funcName = func.Name;

				var parameters = new List<string>();
				foreach (var param in func.Parameters)
				{
					var paramType = Helpers.ConvertParameterType(param.Type);
					var paramName = string.IsNullOrEmpty(param.Name)
						? $"arg{func.Parameters.IndexOf(param)}"
						: Helpers.EscapeReservedKeyword(param.Name);

					// If the parameter type is a delegate name, use the delegate type directly
					if (param.Type is CppPointerType ptr &&
						ptr.ElementType is CppFunctionType)
					{
						// Inline function pointer - try to find matching typedef
						var matchingTypedef = FindMatchingDelegate(ptr, compilation);
						if (matchingTypedef != null)
						{
							paramType = matchingTypedef;
						}
						else
						{
							paramType = "IntPtr";
						}
					}
					else if (param.Type is CppTypedef td && Helpers.DelegateNames.Contains(td.Name))
					{
						paramType = td.Name;
					}

					parameters.Add($"{paramType} {paramName}");
				}

				var paramStr = string.Join(", ", parameters);

				Helpers.WriteComment(writer, func.Comment, "\t\t");
				writer.WriteLine($"\t\t[DllImport(\"{DllName}\", CallingConvention = CallingConvention.Cdecl)]");
				writer.WriteLine($"\t\tpublic static extern {returnType} {funcName}({paramStr});");
				writer.WriteLine();
			}

			writer.WriteLine("\t}");
			writer.WriteLine("}");

			Console.WriteLine($"  Generated: Functions.cs");
		}

		/// <summary>
		/// Try to match an inline function pointer to a named typedef delegate.
		/// </summary>
		private string FindMatchingDelegate(CppPointerType ptrType, CppCompilation compilation)
		{
			if (ptrType.ElementType is not CppFunctionType funcType)
				return null;

			foreach (var td in compilation.Typedefs)
			{
				if (td.ElementType is CppPointerType tdPtr &&
					tdPtr.ElementType is CppFunctionType tdFunc)
				{
					if (FunctionSignaturesMatch(funcType, tdFunc))
					{
						return td.Name;
					}
				}
			}

			return null;
		}

		private bool FunctionSignaturesMatch(CppFunctionType a, CppFunctionType b)
		{
			if (a.Parameters.Count != b.Parameters.Count)
				return false;

			if (a.ReturnType.ToString() != b.ReturnType.ToString())
				return false;

			for (int i = 0; i < a.Parameters.Count; i++)
			{
				if (a.Parameters[i].Type.ToString() != b.Parameters[i].Type.ToString())
					return false;
			}

			return true;
		}
	}
}
