using CppAst;
using System;
using System.Diagnostics;
using System.IO;

namespace JoltPhysicsGen
{
	class Program
	{
		static void Main(string[] args)
		{
			var headersDir = Path.Combine(AppContext.BaseDirectory, "Headers");
			var headerFile = Path.Combine(headersDir, "JoltC", "joltc.h");

			var options = new CppParserOptions
			{
				ParseMacros = true,
				IncludeFolders = { headersDir },
			};

			Console.WriteLine($"Parsing header: {headerFile}");
			var compilation = CppParser.ParseFile(headerFile, options);

			if (compilation.HasErrors)
			{
				foreach (var message in compilation.Diagnostics.Messages)
				{
					if (message.Type == CppLogMessageType.Error)
					{
						Console.ForegroundColor = ConsoleColor.Red;
					}

					Console.WriteLine(message);
					Console.ResetColor();
				}

				// Fatal, because a header the parser could not read produces a smaller
				// binding rather than no binding: the missing declarations simply do not
				// appear, the build succeeds, and the package ships without them. Printing
				// and carrying on made a parse failure look like a successful run.
				Console.Error.WriteLine(
					"Parsing reported errors. Refusing to generate from an incomplete " +
					"compilation.");
				Environment.Exit(1);
			}

			Console.WriteLine($"Enums:     {compilation.Enums.Count}");
			Console.WriteLine($"Classes:   {compilation.Classes.Count}");
			Console.WriteLine($"Functions: {compilation.Functions.Count}");
			Console.WriteLine($"Typedefs:  {compilation.Typedefs.Count}");
			Console.WriteLine($"Macros:    {compilation.Macros.Count}");

			string outputPath = Path.Combine(
				FindRepositoryRoot(),
				"Evergine.Bindings.JoltPhysics", "Generated");

			// Deliberately not created if missing. This used to be a CreateDirectory, which
			// meant a wrong path was silently made rather than reported: under `dotnet publish`
			// the old relative walk landed in JoltPhysicsGen/, the generator wrote five files
			// into a directory nobody reads, exited 0, and the pack used the committed output.
			// Every CD since has published whatever was last generated by hand.
			if (!Directory.Exists(outputPath))
			{
				throw new DirectoryNotFoundException(
					$"Output directory not found: {outputPath}. It is committed to the " +
					"repository, so its absence means the path was resolved wrongly.");
			}

			CsCodeGenerator.Instance.Generate(compilation, outputPath);

			Console.ForegroundColor = ConsoleColor.Green;
			Console.WriteLine($"\nGenerated files written to: {Path.GetFullPath(outputPath)}");
			Console.ResetColor();
		}

		// Anchored on binding.yml rather than a count of "..", because the number of levels
		// depends on how the generator was started: `dotnet run` puts the binary in
		// bin/<cfg>/<tfm>/<rid>/ and `dotnet publish` adds a publish/ below that. Five levels
		// were right for one and off by one for the other, and the one it was wrong for is
		// the one CI and CD use. A marker file cannot drift like that, and it also survives
		// somebody moving a project folder.
		static string FindRepositoryRoot()
		{
			var dir = new DirectoryInfo(AppContext.BaseDirectory);

			while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "binding.yml")))
			{
				dir = dir.Parent;
			}

			if (dir is null)
			{
				throw new DirectoryNotFoundException(
					"Could not find binding.yml walking up from " +
					$"{AppContext.BaseDirectory}. The generator locates its output relative " +
					"to the manifest, so it cannot run outside the repository.");
			}

			return dir.FullName;
		}
	}
}
